### ISSUE TITLE
Empty to select Contract.

### ISSUE THREAD

**Issue by best-lucky1030** [Mintbase/create-mintbase-app#12]
After clone the project and run on my side, I'd like to mint as test.
When I input `tittle`, `description`, `attach image` and click `mint` button, it's not working.
Because there is error with `please select a store`.

![image](https://user-images.githubusercontent.com/89365150/148113478-6509ba1e-4f82-4cc5-81d2-04a370c42b6c.png)

I already created mintbase testnet account.
https://testnet.mintbase.io/human/assassin1030.testnet
I am not sure how can I solve this problem, cuz I am a newbie of using this repo.
Hope someone helps me to do this.

**Comment by microchipgnu** [comment]
Hey! Looks like you're not a minter or owner of any store.

Start by deploying a store: https://testnet.mintbase.io/deploy

**Comment by best-lucky1030** [comment]
I already deployed store and now I am an owner of store.
But contract is not showing.

**Comment by roshaans** [comment]
Create an `.env` file in the root directory and add `NEXT_PUBLIC_MINTBASEJS_NETWORK ="testnet"`
